### ISSUE TITLE
Rewriting in other language

### ISSUE THREAD

**Issue by scoopgracie** [bartekpacia/telegram-lang-enforcer#11]
You'd mentioned Kotlin, but is Python a possibility? It's pretty popular for chat bots.

**Comment by bartekpacia** [comment]
I mentioned Kotlin because it's fully object-oriented.
As of now, TypeScript is great. 
Also, what would be the benefit of rewriting it to Python from TS (except from "Python being pretty popular")?

**Comment by scoopgracie** [comment]
I was thinking Python because it is also OO.

**Comment by bartekpacia** [comment]
Python would be acceptable too. but as I said above, I don't see any significant benefits of rewriting this to Python.

**Comment by scoopgracie** [comment]
I'm saying, what benefits would Kotlin give that Python wouldn't?

**Comment by bartekpacia** [comment]
One of the many is full type safety, when the project will get bigger it'll become increasingly important.

**Comment by bartekpacia** [comment]
Basically if you want, you can create bot_py folder or something, rewrite this in Python and submit a PR.
What I'm trying to say is I'm not going to rewrite it because TypeScript is just fine.

**Comment by scoopgracie** [comment]
Is Python not type safe?

**Comment by bartekpacia** [comment]
It doesn't have a fully sound static type system.

**Comment by scoopgracie** [comment]
Oh, okay. Would it be possibly more feasible to have Python bindings for
backends, so backends could be written in Python?

**Comment by bartekpacia** [comment]
It seems like a good idea. You can do core.py and implementations for any messaging platform you want.

**Comment by scoopgracie** [comment]
Oh, I meant make it so e.g. bot_irc.py could connect to core.ts. Something
like Cython, but TypeScript-Python instead of C-Python.

**Comment by bartekpacia** [comment]
Ah, okay then. I have never thought about such thing. If it I'll work and you provide some decent documentation for it I'll be happy to merge your PR

**Comment by scoopgracie** [comment]
Okay. It looks like Python can easily transpile to JS, so it should work. No bindings to write.

**Comment by scoopgracie** [comment]
I'll use Transcrypt, which is meant for Web development, but should work with this.

**Comment by bartekpacia** [comment]
Okay, good luck! But please try to keep it as simple as possible, because somebody will have to maintain it.

**Comment by scoopgracie** [comment]
Okay.

**Comment by scoopgracie** [comment]
Can this be assumed to always run on UNIX?

**Comment by bartekpacia** [comment]
Ugh...nope.

**Comment by bartekpacia** [comment]
If the price of using Python is being unix-only, then we'd better leave it as-is.

**Comment by scoopgracie** [comment]
Okay. I'll test on Windows too.

**Comment by scoopgracie** [comment]
It won't require that, just asking if my code could use UNIX domain sockets.

**Comment by bartekpacia** [comment]
Okay. I just wanted to emphasize that cross-platform support is important :)

**Comment by scoopgracie** [comment]
Okay. It will be faster on UNIX, but it will fall back to INET sockets on
Windows.

**Comment by bartekpacia** [comment]
I don't quite know what you're talking about but that's great:D

**Comment by bartekpacia** [comment]
We've invested in TypeScript, closing it because it doesn't make any sense,
