### ISSUE TITLE
Add stats and a command to access them

### ISSUE THREAD

**Issue by nikochiko** [bartekpacia/telegram-lang-enforcer#3]
Add functionality to see stats as to how many messages in other langs were detected, and which users did so most frequently etc.

**Comment by bartekpacia** [comment]
@nikochiko Thanks, it looks good, but as of now I'd like to keep DB writes/reads as low as possible because I don't want to exceed the free quota :/

**Comment by nikochiko** [comment]
No probs! We can come back to this later with a different solution. :)

**Comment by nikochiko** [comment]
Closing now
