### ISSUE TITLE
Add a way to create other chat backends?

### ISSUE THREAD

**Issue by scoopgracie** [bartekpacia/telegram-lang-enforcer#8]
Would it be feasible to have the bot's code in one file and the Telegram part in another file, so you could make an alternate backend for, say, IRC?

**Comment by bartekpacia** [comment]
wow, that's a great idea.
We can think about modularizing it.

**Comment by scoopgracie** [comment]
I would like to have something similar for my IRC channel.

**Comment by Uzay-G** [comment]
Maybe it's possible but it would be difficult to modularize considering a big part of it is the interaction with the telegram api

**Comment by bartekpacia** [comment]
on it, check branch [`modularize`](https://github.com/bartekpacia/telegram-lang-enforcer/tree/modularize)

**Comment by scoopgracie** [comment]
Cool! I might make an IRC backend when you're done.

**Comment by bartekpacia** [comment]
okay, I'll let you know when I consider it usable @scoopgracie  :)

**Comment by scoopgracie** [comment]
Did you mean to delete the modularize branch?

**Comment by bartekpacia** [comment]
Yes, I merged everything to master.

**Comment by scoopgracie** [comment]
Oh, okay. Is the modularization already done?

**Comment by bartekpacia** [comment]
Kind of. I split up everything I could. I added some info to the README, I hope you'll find it useful.
